---
- name: Tiny demo
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Create a file with some text
      ansible.builtin.copy:
        content: "Managed by Ansible — hello from {{ inventory_hostname }} on {{ ansible_date_time.date }}\n"
        dest: /tmp/hello_from_ansible.txt
        mode: '0644'