# inventory.ini
[webservers]
localhost           # we also add localhost so you can test without any server

[all:vars]
ansible_user=ubuntu                 # change to your SSH user (ubuntu, ec2-user, centos, root, etc.)
ansible_ssh_private_key_file=~/.ssh/id_rsa   # only needed for real servers

